baseurl                 = "https://edwlarkey.com/"
languageCode            = "en-us"
title                   = "Ed in The Cloud"
theme                   = "hugo-xmin"
preserveTaxonomyNames   = true
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]
ignoreFiles             = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[params]
  description = "Ed in the cloud"
  footer = "&copy; [Edward Larkey](https://edwlarkey.com) {Year} | [GitHub](https://github.com/edwlarkey) | [SourceHut](https://git.sr.ht/&#126;edwlarkey) | [LinkedIn](https://www.linkedin.com/in/edwlarkey)"

[menu]
  [[menu.main]]
    name              = "Home"
    url               = ""
    weight            = 1

  [[menu.main]]
    name              = "About"
    url               = "about/"
    weight            = 2

  [[menu.main]]
    name              = "Categories"
    url               = "categories/"
    weight            = 3

  [[menu.main]]
    name              = "Tags"
    url               = "tags/"
    weight            = 4

  [[menu.main]]
    name              = "RSS"
    url               = "index.xml"
    weight            = 5

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
