version: '2'
services:
  nginx:
    image: edwlarkey/edwlarkey.com
    restart: always
    labels:
      - "traefik.http.routers.edwlarkey.rule=Host(`edwlarkey.com`)"
      - "traefik.http.routers.edwlarkey.entrypoints=websecure"
      - "traefik.http.routers.edwlarkey.service=edwlarkey"
      - "traefik.http.routers.edwlarkey.tls"
      - "traefik.http.services.edwlarkey.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    networks:
      - web
networks:
  web:
    external: true
