version: '2'
services:
  nginx:
    image: edwlarkey/edwlarkey.com
    restart: always
    labels:
      - traefik.backend=edwlarkey.com
      - traefik.port=80
      - traefik.frontend.rule=Host:edwlarkey.com
      - traefik.enable=true
      - traefik.docker.network=web
    networks:
      - web
networks:
  web:
    external: true
